### ISSUE TITLE
Ajout d'un incident : Annulation du vote BDE

### ISSUE THREAD

**Issue by melimea** [epibug/epibug#1]
Nom de l'incident : Annulation du vote BDE

Description : Le BDE ayant principalement effet sur le campus de Paris, seuls les élèves parisiens peuvent participer à son élection. Cependant, le formulaire du scrutin ayant été mal configuré (ouvert aux étudiants en région), le vote a du être annulé puis reconduit la semaine d'après.

Date (YYYY-MM-DD) : 2022-02-11

Mots clefs : 2024, Paris

Importance (high, medium, low) : low

Source : [announcement.ing1](https://news.infinity.study/newsgroups/announcement.ing1?news=%3Csujfge%249lhb%241%40inn-5d779d9897-pdvvf.cri.epita.fr%3E)

**Comment by Dhemis-A** [comment]
Il faut préciser qu'une première victoire a été déclarée le vendredi soir, pour qu'ensuite une victoire de l'autre liste soit déclarée plus tard, avant l'annulation du scrutin pour le nouveau vote.

**Comment by epibug** [comment]
Ajouté dans 89d2378b3f79a063bdb6e20cf8820d0a737326b4. Merci pour votre contribution.
