### ISSUE TITLE
Ajout d'un incident : [Crash Moodle pendant des examens]

### ISSUE THREAD

**Issue by Dhemis-A** [epibug/epibug#2]
Nom de l'incident : Crash Moodle pendant des examens

Description : Un disfonctionement du cri encore inconnu à ce jour a annulé la tenue des rattrapages de sys et net1 sur moodle, et par conséquent les élèves ont du les passer sur papier.

Date (YYYY-MM-DD) : 2022-05-09

Mots clefs : 2024 Exam

Importance (high, medium, low) : Medium

**Comment by epibug** [comment]
Ajouté dans 6b97cdc80bc988bd45a20286078ed03b71aa020f. Merci pour ta contribution.
