### ISSUE TITLE
Ajout d'un incident : Partiel à point négatif en MASI

### ISSUE THREAD

**Issue by Vinetos** [epibug/epibug#3]
Nom de l'incident : Partiel à point négatif en MASI

Description : La scolarité n'est pas en accord avec le fait de faire un examen final à point négatif. Cependant, ce fut le cas, deux fois de suite (cf le crash Moodle du même jour).

Date (YYYY-MM-DD) : 2022-01-03

Mots clefs : MASI

Importance (high, medium, low) : medium

**Comment by epibug** [comment]
Nous étions prévenus à l'avance que MASI allait être un examen à points négatifs. Certes c'est un examen difficile mais cela n'est pas un incident, plus une plainte.
Si j'ai mal interprété ton issue, je te laisse la ré-ouvrir.
