### ISSUE TITLE
Ajouter d'un incident : Engagement étudiant

### ISSUE THREAD

**Issue by Vinetos** [epibug/epibug#4]
Nom de l'incident : Engagement étudiant

Description : La légendre raconte que les étudiants avec un engagement étudiants n'ont toujours pas eu de réponse pour le S6.

Date (YYYY-MM-DD) : 2022-01-03

Mots clefs : engagement etudiant

Importance (high, medium, low) : medium

**Comment by epibug** [comment]
Ajouté dans 378dbce510c47ec054b41851582b4b0893302875. Merci pour ta contribution.
