### ISSUE TITLE
Ajout d'un incident : [NOM]

### ISSUE THREAD

**Issue by Dhemis-A** [epibug/epibug#7]
Nom de l'incident : Déplacement rattrapage  PBS

Description : Le rattrapage devait se dérouler en salle machine sur moodle comme n'importe quel examen. Au dernier moment, l'administration s'est rendu compte que les travaux en cisco allaient rendre la tache insupportable. Tout le monde a ainsi été déplacé dans l'amphi 1 et les sujets moodle ont été imprimé. 

Date (YYYY-MM-DD) : 2022-08-29

Mots clefs : Examen, Travaux

Importance (high, medium, low) : low

**Comment by epibug** [comment]
Ajouté dans d9a9e430fe770451eb81902864bbe92aba9b6ad1. Merci pour ta contribution.
